# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目发起人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.BooleanField(default=False, verbose_name='项目是否确定发布'),
        ),
    ]
