# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='交易号')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单总额')),
                ('pay_status', models.CharField(choices=[('PAYING', '未支付'), ('TRADE_SUCCESS', '支付成功'), ('FAIL', '支付失败')], default='PAYING', max_length=30, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('post_script', models.CharField(blank=True, max_length=200, null=True, verbose_name='订单留言')),
                ('need_invoice', models.BooleanField(default=False, verbose_name='是否需要发票')),
                ('info_invoice', models.CharField(max_length=50, verbose_name='发票抬头')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('support_nums', models.IntegerField(default=0, verbose_name='支持数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='支持时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('support_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.SupportItems', verbose_name='支持的回报项目')),
            ],
            options={
                'verbose_name': '用户支持订单',
                'verbose_name_plural': '用户支持订单',
            },
        ),
    ]
