# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20180925_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='item_nums',
            field=models.IntegerField(default=0, verbose_name='回报数量'),
        ),
    ]
