# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('signer_name', models.CharField(max_length=30, verbose_name='签收人')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name='签收人电话')),
                ('address_nums', models.IntegerField(default=1, verbose_name='地址数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收货地址',
                'verbose_name_plural': '用户收货地址',
            },
        ),
        migrations.CreateModel(
            name='UserLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love_status', models.BooleanField(default=False, verbose_name='关注状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
            ],
            options={
                'verbose_name': '关注信息',
                'verbose_name_plural': '关注信息',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.BooleanField(default=False, verbose_name='当前项目状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发起时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='发起的项目')),
            ],
            options={
                'verbose_name': '发起众筹信息',
                'verbose_name_plural': '发起众筹信息',
            },
        ),
    ]
