# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180925_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project_man',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
